sudo: false

language: python

python:
  - "3.5"
  - "3.6"

services:
  - redis-server

install:
  - pip install -U pip wheel setuptools
  - pip install -e .[tests]
  - pip freeze

script:
  - pytest
  - flake8
  - isort --check-only --recursive asgi_redis tests
  - unify --check-only --recursive --quote \" asgi_redis tests
