sudo: false

language: python

python:
  - "3.5"
  - "3.6"

services:
  - redis-server

install:
  # Temporary pre-release install lines
  - pip install git+https://github.com/django/daphne@2.0
  - pip install git+https://github.com/django/channels@2.0
  - pip install -e .[tests] isort unify flake8
  - pip freeze

script:
  - pytest
  - flake8
  - isort --check-only --recursive asgi_redis tests
  - unify --check-only --recursive --quote \" asgi_redis tests
